## Numpy Array Operations

In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])

# Slicing in array
print("Basic slicing: ", arr[2:8])
print("Slice with step: ", arr[0:8:2])

Basic slicing:  [3 4 5 6 7 8]
Slice with step:  [1 3 5 7]


In [8]:
arr2d = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

# 2d arr indexing --> retrival of a element
print(arr2d[2,0])

# get entire row
print(arr2d[1])

# get entire column
print(arr2d[:,1])


7
[4 5 6]
[2 5 8]


## Sorting in array

In [18]:
unsorted = np.array([3,4,1,6,4,7,9,5,1,3,5,7,0])
print("Sorted array: ", np.sort(unsorted))

unsorted2d = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2d array axis=0: ", np.sort(unsorted2d,axis=0))
print("Sorted 2d array axis=1: ", np.sort(unsorted2d,axis=1))

Sorted array:  [0 1 1 3 3 4 4 5 5 6 7 7 9]
Sorted 2d array axis=0:  [[1 1]
 [2 2]
 [3 3]]
Sorted 2d array axis=1:  [[1 3]
 [1 2]
 [2 3]]


## Array Filtering

In [20]:
arr = np.array([1,2,3,4,5,6,7,8,9])

# Get all even elements
even = arr[arr % 2 == 0]
print("All even elements: ", even)

# Get all odd elements
odd = arr[arr % 2 != 0]
print("Odd elements: ", odd)

All even elements:  [2 4 6 8]
Odd elements:  [1 3 5 7 9]


## np.where() --> conditional function

In [23]:
arr = np.arange(12)
print(arr)

# Printing elements which are greater than 5
cond = np.where(arr > 5)
print(arr[cond])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 6  7  8  9 10 11]


## Adding and removing data

In [29]:
# Concatinate the arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined_arr = np.concatenate((arr1,arr2))
print(combined_arr)


# Deletion of elements
a = np.array([1,2,3,4,5,6,7,8,9])

deleted = np.delete(a,2)  #from array a delete 2 indexed element
print("Array after deleting the 2 index element: ",deleted)

[1 2 3 4 5 6]
Array after deleting the 2 index element:  [1 2 4 5 6 7 8 9]


## Array Compatiblity

In [25]:
a = np.array([1,2,4])
b = np.array([2,3,4])
c = np.array([3,5,6,5])

print("Compatiblity of shape ", a.shape == b.shape)
print("Compatiblity of shape ", a.shape == c.shape)


Compatiblity of shape  True
Compatiblity of shape  False


## Adding new row and columns

In [27]:
# np.vstack() --> used to add rows
# np.hstack() --> used to add columns

og = np.array([[1,2,3] , [4,5,6]])

# ROW --> vstack()
newR = np.array([9,8,7])
withNewR = np.vstack((og , newR))
print(withNewR)


# COLUMNS --> hstack()
newC = np.array([[1],[2]])
withNewC = np.hstack((og , newC))
print(withNewC)

[[1 2 3]
 [4 5 6]
 [9 8 7]]
[[1 2 3 1]
 [4 5 6 2]]
