In [2]:
import numpy as np

## creating arrays

In [ ]:
arr1 = np.array([1,2,3,4,5])    #1D Array
print("Array 1:", arr1)

arr2 = np.array([[1,2,3],[4,5,6]])     #2D Array
print("Array 2: \n",arr2)

Array 1: [1 2 3 4 5]
Array 2: 
 [[1 2 3]
 [4 5 6]]


## Python List  VS Numpy Arrays

In [ ]:
l1 = [1,2,3,4,5]
print("The multiplication of a python list: " , l1*2)   #List Multiplication

a1 = np.array([1,2,3,4,5])
print("The multiplication of a numpy array: " , a1*2)   #Array Multiplication

# Array does element wise operations and take alot less time than lists to execute operations

The multiplication of a python list:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
The multiplication of a numpy array:  [ 2  4  6  8 10]


## Building arrays from scratch using numpy

In [6]:
zeros = np.zeros((3,4))
print("Array of Zeros: \n", zeros)

ones = np.ones((2,2))
print("Array of Ones: \n", ones)

random_array = np.random.random((2,3))
print("Random Array: \n", random_array)

full = np.full((2,3),5)
print("Array full of 5s: \n", full)

Array of Zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array of Ones: 
 [[1. 1.]
 [1. 1.]]
Random Array: 
 [[0.31761926 0.25539523 0.70359027]
 [0.05327319 0.20592855 0.06736904]]
Array full of 5s: 
 [[5 5 5]
 [5 5 5]]


## Vector , Matrix ,Tensor

In [9]:
vector = np.array([1,2,3,4,5,6,7,8,9])
print("Vector:" , vector)

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Matrix: \n" , matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: \n" , tensor)

Vector: [1 2 3 4 5 6 7 8 9]
Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [3]:
arr = np.array([[1,2,3],
                [4,5,6]])
# Shape of array --> Gives number of rows and columns
print("shape: " ,arr.shape)

# Dimension of array --> gives no.of dimension of arrays
print("dimension: ",arr.ndim)

# Size Of Array --> gives total number of elements in array
print("size: ",arr.size)

# Data Type of Array
print("data type: ",arr.dtype)

shape:  (2, 3)
dimension:  2
size:  6
data type:  int64


## Array Reshaping

In [8]:
arr = np.arange(12)
print("Original array: ",arr)

# Reshaping array --> changing shape of array(rows columns)
reshaped = arr.reshape(3,4)
print("Reshaped array: \n",reshaped)

# Flattening array --> converting multi dimensional array to 1D array
flattned = reshaped.flatten()
print("Flattned: ",flattned)

# ravel --> another way to flatten array (it returns view not a copy)
raveled = reshaped.ravel()
print("Raveled: ",raveled)

# Transpose --> interchanging rows and columns
transposed = reshaped.T
print("Transpose: ",transposed)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattned:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
